---
metadata:
  image: "cover.png"
  title: "Sample Project"
  subtitle: "222 Class Project"
  author: 'Gregor von Laszewski'
  subauthor: "Editor"
  email: "laszewski@gmail.com"
  url: "https://github.com/cyberaide/bookmanager"
  description: "Book creator"
  abstract: "my abstract"
  keywords: "pandoc"
  stylesheet: "epub.css"
  dest: "dest/book"
  filename: "vonLaszewski-python.epub"
git:
  "community": "https://raw.githubusercontent.com/cloudmesh-community"
  "book": "https://raw.githubusercontent.com/cloudmesh-community/book/master/chapters"
  "credit": "https://raw.githubusercontent.com/cyberaide/bookmanager/master/bookmanager/template"
  "project-sample": "https://raw.githubusercontent.com/cloudmesh-community/hid-sample/master"
project:
  "report": master/project-report/report.md
  
BOOK:
  - PREFACE:
    - "{git.credit}/disclaimer.md"
  - PROJECT:
    - "{git.project-sample}/project-report/report.md"
    - "{git.community}/sp19-222-89/{project.report}"
    - "{git.community}/sp19-222-90/{project.report}"
    - "{git.community}/sp19-222-92/{project.report}"
    - "{git.community}/sp19-222-95/{project.report}"
    - "{git.community}/sp19-222-96/{project.report}"
    - "{git.community}/sp19-222-97/{project.report}"
    - "{git.community}/sp19-222-100/{project.report}"
    - "{git.community}/sp19-222-101/{project.report}"
